/**
 * Static MG group lookup derived from "MerchGroup Rework - Final Version.csv".
 * Maps MG codes to human-readable descriptions.
 *
 * MG01 description: keyed by mg01_code alone (unique per code across all categories)
 * MG02 description: keyed by "mg01:mg02" (same code can mean different things under different MG01s)
 * MG03 description: keyed by "mg01:mg02:mg03"
 */

/** mgCategory derived from MG01 code (CSV column 1 ↔ column 2 mapping) */
const MG01_CATEGORY: Record<string, string> = {
  A: "Wall", B: "Wall", C: "Wall", D: "Wall", E: "Wall",
  F: "Tabletop", G: "Tabletop", H: "Tabletop", J: "Tabletop", K: "Tabletop",
  M: "Clock",
  N: "Storage", P: "Storage", R: "Storage",
  S: "Workspace", T: "Workspace", U: "Workspace",
  V: "Floor",
  W: "Garden",
};

/** Returns the mgCategory for a given MG01 code, or null if not found. */
export function getMgCategory(mg01: string | null | undefined): string | null {
  if (!mg01) return null;
  return MG01_CATEGORY[mg01] ?? null;
}

const MG01_DESC: Record<string, string> = {
  A: "Stretched/Box",
  B: "Framed",
  C: "Plaque",
  D: "Functional",
  E: "Other Wall",
  F: "Block",
  G: "Box",
  H: "Photo Frames",
  J: "Object",
  K: "Other Tabletop",
  M: "Clocks",
  N: "Soft Storage",
  P: "Hard Storage",
  R: "Other Storage",
  S: "Stationery Org",
  T: "Desk Acc",
  U: "Other Workspace",
  V: "Floor Coverings",
  W: "Garden",
};

const MG02_DESC: Record<string, string> = {
  "A:A": "Canvas",
  "A:S": "Special Material",
  "A:G": "Greyboard",
  "A:F": "Fabric",
  "A:M": "MDF Box",
  "B:F": "Fabric",
  "B:3": "Lenticular/3D",
  "B:G": "Glass",
  "B:J": "Object",
  "B:M": "Mirror",
  "B:R": "Print",
  "C:A": "Plain",
  "C:D": "DIY",
  "C:P": "Leaner",
  "C:R": "Relief/3D Molded",
  "C:S": "Sign",
  "C:T": "Plastic",
  "C:3": "Lenticular",
  "C:9": "Other",
  "D:C": "Countdown Calendar",
  "D:H": "Hook",
  "D:F": "Framed",
  "D:S": "Shelf",
  "D:M": "Memo Board",
  "E:D": "Dimensional",
  "E:H": "Hanging",
  "E:S": "String",
  "E:B": "Box",
  "E:6": "Shades",
  "F:0": "None",
  "F:G": "Glass",
  "F:M": "Monogram",
  "F:E": "LED",
  "F:W": "Word",
  "F:C": "Calendar",
  "G:C": "Ceramic",
  "G:G": "Glass",
  "G:M": "MDF",
  "H:S": "Single",
  "H:C": "Collage",
  "H:F": "Infant",
  "J:B": "Book End",
  "J:C": "Candle",
  "J:P": "Planter",
  "J:R": "Orb",
  "J:D": "Lightup LED",
  "J:E": "Easel",
  "J:G": "Snow Globe",
  "J:U": "Figural",
  "K:B": "Bank",
  "K:9": "Other",
  "M:W": "Wall Clock",
  "M:D": "Desktop Clock",
  "N:H": "Hamper",
  "N:B": "Bin (Shelftop)",
  "N:C": "Chest",
  "N:K": "Basket (floor)",
  "N:T": "Tower/Stand",
  "N:U": "Cube-Collapsible",
  "P:B": "Faux Shaped Box",
  "P:C": "Chest",
  "P:J": "Jewelry/Music Box",
  "P:F": "Lift-off",
  "P:K": "Kitchen",
  "P:N": "Ottoman Non-Collapsible",
  "R:T": "Tray/Dish",
  "S:H": "Single Item Holder",
  "S:P": "Pencil Cup",
  "S:S": "Set",
  "S:M": "Multi Section",
  "S:N": "Phone Stand",
  "S:E": "Headphone Stand",
  "T:C": "Perpetual Calendar",
  "T:M": "Deskmat",
  "T:W": "Paperweight",
  "T:S": "Sticky Note Holder",
  "T:P": "Memo Pad",
  "U:M": "Monitor Stand",
  "U:P": "Lapdesk",
  "V:D": "Door",
  "V:R": "Rug",
  "V:K": "Kitchen",
  "W:D": "Decor",
  "W:T": "Tool",
  "W:A": "Accessory",
};

const MG03_DESC: Record<string, string> = {
  "A:A:0": "None",
  "A:A:1": "Foil",
  "A:A:2": "Shaped",
  "A:A:8": "Other Embellishment",
  "A:A:9": "Other",
  "A:A:B": "Embroidery",
  "A:A:D": "DIY",
  "A:A:E": "LED",
  "A:A:G": "Staggered",
  "A:A:H": "Hi-Gloss",
  "A:A:Q": "Glitter/Sequins/Rhinest",
  "A:A:P": "Handpaint",
  "A:A:Y": "Physical Attachment",
  "A:A:W": "Gel/Other Coat",
  "A:S:N": "Specialty Fabric",
  "A:S:M": "Metallic",
  "A:S:U": "Suede/PU Leather",
  "A:G:E": "LED",
  "A:F:C": "Cross-Stitch",
  "A:F:L": "Linen/Cotton",
  "A:M:0": "None",
  "A:M:D": "Diecut/Attachment",
  "A:M:E": "LED",
  "A:M:Q": "Glitter/Sequins/Rhinest",
  "B:F:C": "Cross-Stitch",
  "B:F:L": "Linen/Cotton",
  "B:F:N": "Specialty Fabric",
  "B:3:G": "Greyboard Frame",
  "B:3:M": "MDF Frame",
  "B:3:S": "Slits / Slats",
  "B:G:D": "LED Infinity",
  "B:G:E": "LED Backlit",
  "B:G:F": "Printed",
  "B:G:Q": "SBox w Glit/Foil",
  "B:G:R": "SBox w Attachment",
  "B:G:W": "Glass Sandwich",
  "B:G:X": "SBox Printed",
  "B:J:B": "Bank",
  "B:J:F": "Fabric/Jersey",
  "B:J:P": "Polyresin",
  "B:J:Y": "Yarn/String",
  "B:M:0": "None",
  "B:M:C": "Diecut MDF",
  "B:M:D": "MDF Frame",
  "B:M:M": "Metal Frame",
  "B:R:0": "None",
  "B:R:1": "Foil",
  "B:R:C": "Collage/Paper",
  "B:R:D": "Diecut/Attachment",
  "B:R:E": "LED",
  "B:R:F": "Fabric",
  "B:R:H": "Handpaint",
  "B:R:M": "MDF Gel Coat",
  "B:R:N": "Natural Frame",
  "B:R:P": "Matting",
  "B:R:Q": "Glitter/Sequins/Rhinest",
  "B:R:S": "Specialty Paper",
  "B:R:T": "Metallic/Holofoil",
  "B:R:Y": "Shaped/Molded Frame",
  "C:A:0": "None",
  "C:A:A": "Attachment",
  "C:A:C": "Diecut",
  "C:A:H": "Holofoil",
  "C:A:Q": "Foil",
  "C:A:S": "Specialty Paper",
  "C:D:0": "None",
  "C:P:0": "None",
  "C:P:C": "Diecut",
  "C:P:E": "LED",
  "C:P:G": "Glow-in-the-dark",
  "C:P:Q": "Glitter",
  "C:R:F": "Foam/Felt",
  "C:R:M": "MDF",
  "C:S:3": "Door Hanger Lentic",
  "C:S:D": "Door Hanger MDF",
  "C:S:G": "Glass",
  "C:S:M": "Metal Sign",
  "C:S:W": "Wall Hanger MDF",
  "C:T:D": "LED",
  "C:T:S": "Suncatcher",
  "C:3:M": "On MDF",
  "C:3:0": "None",
  "C:9:C": "Cork",
  "C:9:N": "Natural",
  "D:C:0": "None",
  "D:H:M": "Single MDF",
  "D:H:U": "Multi MDF",
  "D:F:0": "None",
  "D:F:C": "Cork",
  "D:F:D": "Dry-Erase",
  "D:F:P": "Pinboard",
  "D:F:T": "Letterboard",
  "D:S:M": "MDF",
  "D:S:N": "Natural",
  "D:S:P": "Plastic",
  "D:S:W": "Woven",
  "D:M:D": "Dry-Erase/Magnetic",
  "E:D:N": "Natural",
  "E:D:P": "Plastic",
  "E:D:R": "Paper Rope",
  "E:H:B": "Banner",
  "E:H:P": "Pennant",
  "E:H:T": "Tapestry",
  "E:H:S": "Scroll",
  "E:S:B": "Banner/Bunting/Pennant",
  "E:S:C": "Clip/Photo Holder",
  "E:S:S": "String Light LED",
  "E:B:D": "LED",
  "E:6:P": "Paper",
  "F:0:M": "MDF",
  "F:G:0": "None",
  "F:M:G": "Greyboard",
  "F:M:M": "MDF",
  "F:M:N": "Natural",
  "F:M:P": "Plush/Fabric",
  "F:E:M": "MDF",
  "F:W:M": "MDF",
  "F:C:M": "MDF",
  "G:C:0": "None",
  "G:G:J": "Jewelry",
  "G:M:0": "None",
  "G:M:1": "Foil",
  "G:M:E": "LED",
  "G:M:R": "Raised/Diecut",
  "G:M:Q": "Glitter",
  "G:M:S": "Paint Stroke",
  "H:S:F": "Fabric",
  "H:S:R": "Diecut/Attachment",
  "H:C:F": "Fabric",
  "H:C:R": "Diecut/Attachment",
  "H:F:2": "12 Month Collage",
  "H:F:C": "Clay/Ink",
  "J:B:C": "Ceramic/Polyresin",
  "J:C:R": "Holder/Polyresin",
  "J:P:C": "Ceramic",
  "J:R:K": "Terracotta",
  "J:D:E": "Etched Acrylic",
  "J:D:G": "Glass",
  "J:D:P": "Plastic",
  "J:E:D": "Dry-Erase",
  "J:G:0": "None",
  "J:U:W": "Woven",
  "K:B:C": "Ceramic",
  "K:B:M": "MDF",
  "K:9:M": "Mug",
  "M:W:B": "Basic Plastic",
  "M:W:C": "Diecut MDF",
  "M:W:M": "Round MDF",
  "M:W:N": "Countdown MDF",
  "M:W:S": "Metal",
  "M:D:A": "Vintage Alarm",
  "M:D:S": "Metal",
  "N:H:2": "Oxford+PE Coat",
  "N:H:F": "Felt",
  "N:H:M": "Polymesh",
  "N:H:N": "Poly/Linen+EVA",
  "N:H:P": "PU/Plastic+EVA",
  "N:H:X": "Oxford+Greyb",
  "N:H:W": "Nonwoven+Greyb",
  "N:B:X": "Oxford",
  "N:C:X": "Oxford",
  "N:K:P": "Paper Seagrass",
  "N:K:R": "Rope",
  "N:T:S": "Steel w Nonwoven",
  "N:T:W": "Steel w Woven",
  "N:U:N": "Nonwoven",
  "N:U:T": "Ottoman/Oxford",
  "P:B:G": "Greyboard Book",
  "P:B:M": "MDF Book",
  "P:B:U": "Greyboard Suitcase",
  "P:C:G": "Greyboard",
  "P:C:Q": "Emb Greyboard",
  "P:J:G": "Greyboard",
  "P:J:S": "Glass",
  "P:F:Q": "Emb Greyboard",
  "P:K:P": "Plastic",
  "P:N:M": "MDF",
  "R:T:A": "Acrylic",
  "R:T:C": "Ceramic/Polyresin",
  "R:T:G": "Glass",
  "R:T:W": "Wood",
  "S:H:P": "Paper Items",
  "S:P:A": "Acrylic",
  "S:P:C": "Ceramic/Polyresin",
  "S:P:G": "Greyboard",
  "S:P:M": "MDF",
  "S:S:M": "MDF",
  "S:M:A": "Acrylic",
  "S:M:G": "Greyboard",
  "S:M:S": "Metal",
  "S:H:F": "Fabric",
  "S:N:M": "MDF",
  "S:N:P": "Plastic",
  "S:E:S": "Metal",
  "T:C:M": "MDF",
  "T:M:R": "Rubber",
  "T:W:G": "Glass",
  "T:S:C": "Ceramic/Polyresin",
  "T:P:C": "Ceramic/Polyresin",
  "U:M:0": "None",
  "U:P:0": "None",
  "V:D:C": "Coir w/ Plain Print",
  "V:D:D": "Coir w/ Emboss",
  "V:D:E": "Coir Diecut",
  "V:D:R": "Rubber w/ Plain Print",
  "V:D:U": "TPE w/ Print",
  "V:D:Q": "Rubber w/ Embossed",
  "V:D:T": "TPE w/ Diecut",
  "V:R:A": "Rabbit Fur Rectang",
  "V:R:R": "Rabbit Fur Diecut",
  "V:R:T": "Throw, Loop",
  "V:K:P": "PVC Foam",
  "W:D:H": "Birdhouse",
  "W:D:P": "Plastic",
  "W:D:S": "Stepping Stone",
  "W:D:T": "Planter",
  "W:D:X": "Oxford",
  "W:T:8": "Metal Tool Set",
  "W:T:T": "Thermometer",
  "W:T:W": "Watering Can",
  "W:A:G": "Glove",
  "W:A:8": "Accessory Set",
};

export function getMg01Desc(mg01: string | null | undefined): string | null {
  if (!mg01) return null;
  return MG01_DESC[mg01] ?? null;
}

export function getMg02Desc(mg01: string | null | undefined, mg02: string | null | undefined): string | null {
  if (!mg01 || !mg02) return null;
  return MG02_DESC[`${mg01}:${mg02}`] ?? null;
}

export function getMg03Desc(mg01: string | null | undefined, mg02: string | null | undefined, mg03: string | null | undefined): string | null {
  if (!mg01 || !mg02 || !mg03) return null;
  return MG03_DESC[`${mg01}:${mg02}:${mg03}`] ?? null;
}

export type MgOption = {
  code: string;
  name: string;
};

export function getMg01Options(): MgOption[] {
  return Object.entries(MG01_DESC)
    .map(([code, name]) => ({ code, name }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function getMg02Options(mg01: string | null | undefined): MgOption[] {
  if (!mg01) return [];
  const prefix = `${mg01}:`;
  return Object.entries(MG02_DESC)
    .filter(([key]) => key.startsWith(prefix))
    .map(([key, name]) => ({ code: key.slice(prefix.length), name }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function getMg03Options(mg01: string | null | undefined, mg02: string | null | undefined): MgOption[] {
  if (!mg01 || !mg02) return [];
  const prefix = `${mg01}:${mg02}:`;
  return Object.entries(MG03_DESC)
    .filter(([key]) => key.startsWith(prefix))
    .map(([key, name]) => ({ code: key.slice(prefix.length), name }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
