export {
  ASSET_TAG_CATEGORIES,
  GROUP_TAG_CATEGORIES,
  TAG_STATUSES,
  TAG_SOURCE_PRIORITY,
  AUTHORITATIVE_TAG_SOURCE,
  AUTHORITATIVE_TAG_MODEL,
  authoritativeTagsAreCurrent,
  GROUP_AI_AUTO_PROMOTION_CONFIDENCE,
  GROUP_AI_AUTO_PROMOTION_MIN_EVIDENCE,
  normalizeMetadataTag,
  sourcePriority,
  groupAiStatus,
  deriveAuthoritativeGroupTags,
} from "../../../supabase/functions/_shared/tagging-metadata-policy.js";
