/**
 * Pre-May-14-2025 MerchGroup meanings (flat, per division), from the ColdLion
 * exports in Dropbox ai/old_merch. Before the rework MG01 was material, MG02
 * product type and MG03 finish; the same letters mean different things now.
 */

/** Items created before this date use the legacy meanings. */
export const MG_REWORK_CUTOFF = "2025-05-14";

const LEGACY: Record<string, Record<string, Record<string, string>>> = {
  CW001: {
    "01": {
      "0": "OTHER",
      "2": "SUEDE",
      "3": "LENTICULAR",
      "7": "YARN",
      "8": "PU LEATHER",
      "A": "LEATHER/COWHIDE",
      "B": "GREYBOARD",
      "C": "CERAMIC",
      "D": "DRY ERASE",
      "E": "FELT",
      "F": "FOAM",
      "G": "GLASS",
      "H": "FABRIC",
      "J": "DENIM",
      "K": "CORK",
      "M": "MDF",
      "N": "SILICONE",
      "P": "PLASTIC",
      "R": "PAPER",
      "S": "METAL",
      "U": "PLUSH",
      "V": "CANVAS",
      "W": "WOOD",
      "Y": "POLYRESIN",
    },
    "02": {
      "6": "DECAL",
      "A": "GARDEN",
      "B": "BOX",
      "D": "WORKSPACE/DESK",
      "E": "LETTER/WORD",
      "F": "FRAMED",
      "G": "STORAGE",
      "H": "SHELVING",
      "J": "OTHER DECOR",
      "K": "KITCHEN",
      "N": "BANNER/PENNANT",
      "P": "PRINT",
      "Q": "PLAQUE",
      "R": "SCROLL",
      "S": "STRETCHED",
      "T": "TABLETOP DECOR",
      "W": "SHADES",
      "X": "FLOOR COVERING",
      "Z": "STRING",
    },
    "03": {
      "1": "FOIL",
      "2": "MULTI-LAYER",
      "3": "MIRROR",
      "A": "ATTACHMENT",
      "B": "BANK",
      "C": "DIECUT",
      "D": "STATIONERY DESK ORG",
      "E": "LED",
      "H": "HI-GLOSS",
      "S": "HAND PAINT",
      "X": "MOLDED/EMBOSSED",
      "F": "FLOATING",
      "G": "COLLAGE",
      "K": "CLOCK",
      "M": "METALLIC",
      "N": "MULTI-PIECE",
      "P": "FUNCTIONAL",
      "Q": "GLITTER/SPARKLE/SEQUIN",
      "R": "INSPIRATIONAL",
      "T": "SLITS",
      "U": "SPECIALTY MATERIAL",
      "V": "STAGGERED",
      "W": "GEL/GLOW",
      "Y": "DIY",
      "Z": "NONE",
    },
  },
  EH001: {
    "01": {
      "0": "OTHER",
      "2": "SUEDE",
      "3": "LENTICULAR",
      "7": "YARN/STRING",
      "8": "PU LEATHER",
      "A": "LEATHER/COWHIDE",
      "B": "GREYBOARD",
      "C": "CERAMIC",
      "D": "DRY ERASE",
      "E": "FELT",
      "F": "FOAM",
      "G": "GLASS",
      "H": "FABRIC",
      "J": "DENIM",
      "K": "CORK",
      "M": "MDF",
      "N": "SILICONE",
      "P": "PLASTIC",
      "R": "PAPER",
      "S": "STEEL",
      "U": "PLUSH",
      "V": "CANVAS",
      "W": "WOOD",
      "Y": "POLYRESIN",
    },
    "02": {
      "6": "DECAL",
      "B": "BOX",
      "C": "CUBE, BLOCK, TRIANGLE",
      "D": "WORKSPACE/DESK",
      "E": "LETTER/WORD",
      "F": "FRAMED",
      "G": "STORAGE",
      "H": "SHELVING",
      "J": "OTHER DECOR",
      "K": "KITCHEN",
      "N": "BANNER/PENNANT",
      "P": "PRINT",
      "Q": "PLAQUE",
      "R": "SCROLL",
      "S": "STRETCHED",
      "T": "TABLETOP",
      "W": "SHADES",
      "X": "FLOOR COVERING",
      "Z": "STRING",
    },
    "03": {
      "1": "FOIL",
      "2": "MULTI-LAYER",
      "A": "ATTACHMENT",
      "B": "BANK",
      "C": "DIECUT",
      "D": "STATIONERY DESK ORG",
      "E": "LED",
      "H": "HI GLOSS",
      "S": "HAND PAINT",
      "X": "MOLDED/EMBOSSED",
      "F": "FLOATING",
      "G": "COLLAGE",
      "M": "METALLIC",
      "N": "PRINT EMBLSH",
      "P": "FUNCTIONAL",
      "Q": "GLITTER/SPARKLE/SEQUIN",
      "T": "SLITS",
      "U": "SUEDE/SATIN",
      "W": "GEL/GLOW",
      "Y": "DIY",
      "Z": "NONE",
    },
  },
};

export function getLegacyMgDesc(
  division: string,
  mgType: "01" | "02" | "03",
  code: string | null | undefined,
): string | null {
  if (!code) return null;
  return (LEGACY[division] ?? LEGACY.CW001)[mgType][code] ?? null;
}
