
ALTER TABLE public.assets
  ADD COLUMN IF NOT EXISTS sku TEXT,
  ADD COLUMN IF NOT EXISTS mg01_code TEXT,
  ADD COLUMN IF NOT EXISTS mg01_name TEXT,
  ADD COLUMN IF NOT EXISTS mg02_code TEXT,
  ADD COLUMN IF NOT EXISTS mg02_name TEXT,
  ADD COLUMN IF NOT EXISTS mg03_code TEXT,
  ADD COLUMN IF NOT EXISTS mg03_name TEXT,
  ADD COLUMN IF NOT EXISTS size_code TEXT,
  ADD COLUMN IF NOT EXISTS size_name TEXT,
  ADD COLUMN IF NOT EXISTS licensor_code TEXT,
  ADD COLUMN IF NOT EXISTS licensor_name TEXT,
  ADD COLUMN IF NOT EXISTS property_code TEXT,
  ADD COLUMN IF NOT EXISTS property_name TEXT,
  ADD COLUMN IF NOT EXISTS sku_sequence TEXT,
  ADD COLUMN IF NOT EXISTS product_category TEXT,
  ADD COLUMN IF NOT EXISTS division_code TEXT,
  ADD COLUMN IF NOT EXISTS division_name TEXT;
